var annotated_dup =
[
    [ "AlgorithmDecorator", "classAlgorithmDecorator.html", "classAlgorithmDecorator" ],
    [ "BubbleSort", "classBubbleSort.html", "classBubbleSort" ],
    [ "BubbleSortCommand", "classBubbleSortCommand.html", "classBubbleSortCommand" ],
    [ "Caretaker", "classCaretaker.html", "classCaretaker" ],
    [ "Command", "classCommand.html", "classCommand" ],
    [ "ConsoleApp", "classConsoleApp.html", "classConsoleApp" ],
    [ "DataBuilder", "classDataBuilder.html", "classDataBuilder" ],
    [ "DataDirector", "classDataDirector.html", "classDataDirector" ],
    [ "DataFactory", "classDataFactory.html", null ],
    [ "DataManager", "classDataManager.html", "classDataManager" ],
    [ "DataVisitor", "classDataVisitor.html", "classDataVisitor" ],
    [ "GenerateDataCommand", "classGenerateDataCommand.html", "classGenerateDataCommand" ],
    [ "GUIBubbleSortCommand", "classGUIBubbleSortCommand.html", "classGUIBubbleSortCommand" ],
    [ "GUICommand", "classGUICommand.html", "classGUICommand" ],
    [ "GUIGenerateDataCommand", "classGUIGenerateDataCommand.html", "classGUIGenerateDataCommand" ],
    [ "GUIInputDataCommand", "classGUIInputDataCommand.html", "classGUIInputDataCommand" ],
    [ "GUILoadCommand", "classGUILoadCommand.html", "classGUILoadCommand" ],
    [ "GUIQuickSortCommand", "classGUIQuickSortCommand.html", "classGUIQuickSortCommand" ],
    [ "GUISaveCommand", "classGUISaveCommand.html", "classGUISaveCommand" ],
    [ "InputDataCommand", "classInputDataCommand.html", "classInputDataCommand" ],
    [ "ISortStrategy", "classISortStrategy.html", "classISortStrategy" ],
    [ "LoadCommand", "classLoadCommand.html", "classLoadCommand" ],
    [ "LoggingObserver", "classLoggingObserver.html", "classLoggingObserver" ],
    [ "Memento", "classMemento.html", "classMemento" ],
    [ "Observer", "classObserver.html", "classObserver" ],
    [ "PrintVisitor", "classPrintVisitor.html", "classPrintVisitor" ],
    [ "QuickSort", "classQuickSort.html", "classQuickSort" ],
    [ "QuickSortCommand", "classQuickSortCommand.html", "classQuickSortCommand" ],
    [ "SaveCommand", "classSaveCommand.html", "classSaveCommand" ],
    [ "SortTemplate", "classSortTemplate.html", "classSortTemplate" ],
    [ "Subject", "classSubject.html", "classSubject" ],
    [ "SumVisitor", "classSumVisitor.html", "classSumVisitor" ],
    [ "TimingDecorator", "classTimingDecorator.html", "classTimingDecorator" ],
    [ "UIObserver", "classUIObserver.html", "classUIObserver" ]
];